apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-webserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/j-insan3/gitops-demo.git
    targetRevision: HEAD
    path: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
